############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
URL = "apropos"
name = "À propos"
weight = 2

[[main]]
URL = "galerie"
name = "Galerie"
weight = 3

[[main]]
URL = "blog"
name = "Blog"
weight = 4

[[main]]
URL = "prestations"
name = "Prestations"
weight = "5"

[[main]]
URL = "contact"
name = "Contact"
weight = "6"

# footer menu
[[footer]]
URL = "apropos"
name = "À propos"
weight = 1

[[footer]]
URL = "galerie"
name = "Galerie"
weight = "2"

[[footer]]
URL = "prestations"
name = "Prestations"
weight = 3

[[footer]]
URL = "contact"
name = "Contact"
weight = "4"
