############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
URL = "blog"
name = "Blog"
weight = 2

[[main]]
URL = "adoption"
name = "Chats à l'adoption"
weight = 3

[[main]]
URL = "nousaider"
name = "Nous aider"
weight = 4

[[main]]
URL = "contact"
name = "Contact"
weight = 5

# footer menu
[[footer]]
name = "Accueil"
url = ""
weight = 1

[[footer]]
URL = "blog"
name = "Blog"
weight = 2

[[footer]]
URL = "adoption"
name = "Chats à l'adoption"
weight = 3

[[footer]]
URL = "nousaider"
name = "Nous aider"
weight = 4

[[footer]]
URL = "contact"
name = "Contact"
weight = 5
