backend:
  name: git-gateway
  branch: master 
media_folder: "unchatunchat/static/images"
public_folder: "/images"
collections:
  - name: "blog" 
    label: "Article" 
    folder: "unchatunchat/content/french/blog" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Un chat un chat" }
      - { label: "BG image", name: "bg_image", widget: "image", default: "images/bandeau_blog.png"}
      - { label: "Featured Image", name: "image", widget: "image" }
      - { type: "Type", name: "type", widget: "string", default: "post" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false } 
      - { label: "Categories", name: "categories", widget: "list"} 
      - { label: "Tags", name: "tags", widget: "list"} 
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "adoption" # Used in routes, e.g., /admin/collections/blog
    label: "Adoption" # Used in the UI
    folder: "unchatunchat/content/french/adoption" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - { label: "Title", name: "title", widget: "string", default: "[le nom du chat]"}
      - { label: "Description", name: "description", widget: "string", default: "En savoir plus sur [le nom du chat]" }
      - { label: "BG image", name: "bg_image", widget: "image", default: "siteinternetbandeau.png"}
      - { label: "Featured Image", name: "image", widget: "image" }
      - { type: "Weight", name: "weight", widget: "number" }
      - { label: "Adopted", name: "adopted", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false } 
      - { label: "Gone", name: "gone", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
